services:
  postgres:
    container_name: postgres
    image: postgres:16.6-alpine3.21
    restart: always
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
      - logging
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
