# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateAll(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.OverallResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateAll", llm_response=llm_response, mode="request")
        return typing.cast(types.OverallResult, result)

    def EvaluateProject(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ProjectEvaluationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateProject", llm_response=llm_response, mode="request")
        return typing.cast(types.ProjectEvaluationResult, result)

    def ExtractCV(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CVExtractionResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCV", llm_response=llm_response, mode="request")
        return typing.cast(types.CVExtractionResult, result)

    def ExtractJobDescription(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.JobDescription:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractJobDescription", llm_response=llm_response, mode="request")
        return typing.cast(types.JobDescription, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluateAll(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.OverallResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateAll", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.OverallResult, result)

    def EvaluateProject(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ProjectEvaluationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateProject", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ProjectEvaluationResult, result)

    def ExtractCV(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CVExtractionResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCV", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CVExtractionResult, result)

    def ExtractJobDescription(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.JobDescription:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractJobDescription", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.JobDescription, result)

    