# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CVExtractionResult": types.CVExtractionResult,
    "stream_types.CVExtractionResult": stream_types.CVExtractionResult,

    "types.Education": types.Education,
    "stream_types.Education": stream_types.Education,

    "types.Experience": types.Experience,
    "stream_types.Experience": stream_types.Experience,

    "types.JobDescription": types.JobDescription,
    "stream_types.JobDescription": stream_types.JobDescription,

    "types.OverallResult": types.OverallResult,
    "stream_types.OverallResult": stream_types.OverallResult,

    "types.Project": types.Project,
    "stream_types.Project": stream_types.Project,

    "types.ProjectEvaluationResult": types.ProjectEvaluationResult,
    "stream_types.ProjectEvaluationResult": stream_types.ProjectEvaluationResult,

    "types.SkillResult": types.SkillResult,
    "stream_types.SkillResult": stream_types.SkillResult,


}