# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Education": types.Education,
    "stream_types.Education": stream_types.Education,

    "types.Experience": types.Experience,
    "stream_types.Experience": stream_types.Experience,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


}